### PR TITLE
fix(message-parser): Added ChannelMention in the markup

### PR DESCRIPTION
**Pull request by brf153**
# fix(markup-problem): 

Added ChannelMention in the type Markup

- I have read the Contributing Guide - https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat doc
- I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
- Lint and unit tests pass locally with my changes
- I have labeled the PR correctly with the related package
- Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

Initially, the bold, strike, and italic markup was not working on the mobile while mentioning the channel name in the message box.
Screenshot from 2023-11-06 16-53-18

I have made the necessary changes in the React Native repo but there is a specific change that is required in the fuselage repo as well for that change to work. We need to add ChannelMention in the type Markup for this change to work. I have made these changes and raising the PR for the same.

After adding the changes, we would be able to see the Channel in the message box.
WhatsApp Image 2023-11-06 at 17 04 13

## Issue(s)

https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5305

### CODE REVIEW

**Review by GleidsonDaniel — APPROVED** [review]

**Review by hugocostadev — DISMISSED** [review]

**Comment by casalsgh** [comment]
@brf153 thanks for the contribution. Seems CLA was not signed. Can you double-check if you agree and if you do, sign it?

**Comment by brf153** [comment]
@casalsgh is it signed now?

**Review by ggazzo — DISMISSED** [review]
please adjust the title following conventional commits rules

**Comment by brf153** [comment]
@ggazzo 

> Please adjust the title following conventional commit rules

I did not get it. What is the conventional commit rule and which particular aspect of the commit message does the term 'title' refer to?

**Comment by brf153** [comment]
@ggazzo Has everything been completed? Are there any remaining modifications to be made?

**Review by hugocostadev — APPROVED** [review]

**Comment by casalsgh** [comment]
Thanks for the PR @brf153 😁👏
About the conventional commit rules, please check this link: https://www.conventionalcommits.org/en/v1.0.0/#:~:text=The%20Conventional%20Commits%20specification%20is,automated%20tools%20on%20top%20of.

**Pull request merged**
