### PR TITLE
fix(message-parser): Link are not clickable if local environment

### PR DESCRIPTION
**Pull request by IllTamer**
### Before
image

### Now
image

## Issue(s)
closes https://github.com/RocketChat/Rocket.Chat/issues/28427

## Further comments
- I have utilized an array to store approved local URL suffixes that may facilitate any future extensions.
- Thanks for @dudanogueira 's help lol

### CODE REVIEW

**Comment by yash-rajpal** [comment]
Hey @IllTamer! This looks good to me, can you also add some tests? 

Hint - Check file `message-parser/tests/link.test.ts`

Thanks for the contribution.

**Comment by IllTamer** [comment]
> Hey @IllTamer! This looks good to me, can you also add some tests?
> 
> Hint - Check file `message-parser/tests/link.test.ts`
> 
> Thanks for the contribution.

Of course : )

**Comment by hugocostadev** [comment]
Sorry @IllTamer but this cannot be done statically like that, since it's an internal host... I'm trying to find a way to add this dynamically with parser options.

My idea is: to add a new setting to Rocket.Chat with acceptable hosts and dynamically send to the message parser to add to the function. You are welcome to help if possible

**Comment by hugocostadev** [comment]
FYI: I got to make it work, I'll open a PR soon! 🥳 🚀 

image

image

**Pull request closed without merging**
