### PR TITLE
fix(message-parser): mentions and emojis inside bold, italic and strikethrough

### PR DESCRIPTION
**Pull request by jayesh-jain252**
## Proposed changes (including videos or screenshots)

Mentions and emojis are not parsed when they are inside bold, italic or strikethrough

After:

[mentions.webm](https://user-images.githubusercontent.com/79307894/234263431-a561edf0-f4ba-4b63-9b3d-acb84e65b283.webm)

Channel Mentions

Channel Mention

Emojis

[Unicode Emoji.webm](https://user-images.githubusercontent.com/79307894/234262400-7114e1eb-9918-4505-ab20-254e3e1c9c94.webm)

Unicode

Emoticons

emoticon_bold_italic_strike

## Issue(s)

https://github.com/RocketChat/Rocket.Chat/issues/27838
https://github.com/RocketChat/Rocket.Chat/issues/27839
https://github.com/RocketChat/Rocket.Chat/issues/28843

## Further comments

Modifications:
* Added tests for these cases and added `Emoji | UserMention | ChannelMention` to Bold, Italic, Strike definitions
* Modified grammar.pegjs to support emojis and mentions. I added Whitespace, UserMention, ChannelMention, Emoji, Emoticon Rules.

For testing in Rocket.Chat application, modify gazzodown package  (e.g. Rocket.Chat/packages/gazzodown/src/elements/BoldSpan.tsx)

```
// . . . 
// add imports for mentions and emojis
import EmojiElement from '../emoji/EmojiElement';
import ChannelMentionElement from '../mentions/ChannelMentionElement';
import UserMentionElement from '../mentions/UserMentionElement';

// Modify type to include emojis and mention
type BoldSpanProps = {
	children: ( MessageParser.Emoji | MessageParser.ChannelMention | MessageParser.UserMention | MessageParser.Link | MessageParser.MarkupExcluding<MessageParser.Bold>
        )[];
};

const BoldSpan = ({ children }: BoldSpanProps): ReactElement => (
	<strong>
		{children.map((block, index) => {
			switch (block.type) {
                                // . . .
				// add cases to support mentions and emojis
                                case 'MENTION_USER':
					return <UserMentionElement key={index} mention={block.value.value} />;

				case 'MENTION_CHANNEL':
					return <ChannelMentionElement key={index} mention={block.value.value} />;

				case 'EMOJI':
					return <EmojiElement key={index} {...block} />;

				default:
					return null;
			}
		})}
	</strong>
);

export default BoldSpan;

```

### CODE REVIEW

**Comment by jayesh-jain252** [comment]
@tassoevan. I'm a bit unsure about marking my pr as "Ready for review" because some of the tests are failing. Can you please advise me on what I should do in this situation?

**Comment by hugocostadev** [comment]
Hi @jayesh-jain252 thanks a lot for your contribution 🚀 

I'm taking a look here, and the tasks that are failing it's important to fix, we had to avoid generating `Emphasis` elements with only whitespace inside. 

I'll try to figure out here, but just as a note, we need to fix those

**Comment by jayesh-jain252** [comment]
For Instant Testing:
Copy this grammar code from here: https://gist.github.com/jayesh-jain252/522356f9f375ccbd0ab60136080d5fbd
Paste this code at Peggyjs Online version - https://peggyjs.org/online.html

Problem (taking example for bold text):
As I modified the code and added the Whitespace rule to support UserMention/ChannelMention in Bold

Example: For input `* *`
We should get

image


We are getting

image

So for user inputs with only blank spaces, our grammar should not treat them as emphasis but as plain text.

I tried modifying AnyBold Rule to address this issue, but that resulted in more tests failing. If there's a way we could solve this issue do let me know.

You can modify the grammar at Peggy online for testing

image

For this [grammar](https://gist.github.com/jayesh-jain252/522356f9f375ccbd0ab60136080d5fbd) I took the top part of the code from [rocketchat-pegjs-benchmark by hugocostadev](https://github.com/hugocostadev/rocketchat-pegjs-benchmark/blob/master/rocketchat/grammar_PR_Refactor/grammar_PR_Refactor.pegjs) and rest from current message-parse grammar.

**Comment by jayesh-jain252** [comment]
> For Instant Testing: Copy this grammar code from here: https://gist.github.com/jayesh-jain252/522356f9f375ccbd0ab60136080d5fbd Paste this code at Peggyjs Online version - https://peggyjs.org/online.html
> 
> Problem (taking example for bold text): As I modified the code and added the Whitespace rule to support UserMention/ChannelMention in Bold
> 
> Example: For input `* *` We should get

@hugocostadev Could you point me to any resources or give me a hint on how to approach the solution? Thanks in advance!

**Comment by jayesh-jain252** [comment]
> For Instant Testing: Copy this grammar code from here: https://gist.github.com/jayesh-jain252/522356f9f375ccbd0ab60136080d5fbd Paste this code at Peggyjs Online version - https://peggyjs.org/online.html
> 
> Problem (taking example for bold text): As I modified the code and added the Whitespace rule to support UserMention/ChannelMention in Bold
> 
> Example: For input `* *` We should get

@hugocostadev ,The Whitespace rule I added is responsible for these test cases to fail, but for supporting user/channel mentions I added it. Would love to hear your thoughts and suggestions on this. 😊

**Comment by jayesh-jain252** [comment]
@hugocostadev now all the tests are passing. I've added an `EmphasisWithWhitespace` rule to the code. This rule checks for inputs that are of type `* *,  ** **,  _ _`.
Could you please review my changes and let me know if you have any feedback?

**Comment by hugocostadev** [comment]
Awesome @jayesh-jain252 everything is working now, thanks a lot for your effort!

**Review by hugocostadev — APPROVED** [review]

**Comment by hugocostadev** [comment]
@jayesh-jain252 can you open a PR in Rocket.Chat making the changes in the Gazzodown ?

**Comment by jayesh-jain252** [comment]
Thanks for the approval @hugocostadev 🚀. Opened the PR with changes in the gazzodown package https://github.com/RocketChat/Rocket.Chat/pull/29391

**Pull request merged**
